### PR TITLE
Add CI pipeline

### PR DESCRIPTION
**Pull request by ddugovic**
GitHub can compile and run your code each time you commit changes:
https://github.com/features/actions

### CODE REVIEW

**Comment by Luecx** [comment]
what exactly is the effect of this? I have never seen that before. Could you briefly summarise the benefits of that?

**Comment by ddugovic** [comment]
The effect of this is that https://github.com/Luecx/Koivisto/actions will show which of your code changes can compile on someone else's machine (in this case, on Ubuntu; it's possible to write configurations to compile on other operating systems), and how quickly they pass whatever tests you choose to write.

**Comment by Luecx** [comment]
ah that actually makes sense! Thank you very much for your contribution :)

**Comment by ddugovic** [comment]
Glad to contribute what I know; thanks for making an open source engine to play on Lichess!

**Comment by Eugenio-Bruno** [comment]
Thanks @ddugovic for the help!

We actually use the makefile inside src_files for builds and testing, the CMakeFile is to have ide support (I think). I assume it should be even simpler to change the action to test that?

**Comment by ddugovic** [comment]
Maybe that would be simpler; feel free to edit `cmake.yml` and/or add more configuration files, although I would assume both the makefile and the CMakeFile should function the same way.

**Pull request merged**
